// Generated by Wrangler on Thu Jun 06 2024 14:43:22 GMT-0400 (Chile Standard Time)
// by running `wrangler types`

interface Env {
	MY_VARIABLE: "test";
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
}
