// Generated by Wrangler on Sat Jun 08 2024 16:40:55 GMT-0400 (Chile Standard Time)
// by running `wrangler types`

interface Env {
	MY_VARIABLE: "test";
	MODE: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
}
